from typing import List, Optional, Any, Dict
from fastapi import APIRouter, Depends, HTTPException, status, Body
from sqlalchemy.orm import Session
import decimal

from weezy_cbs.database import get_db
from . import schemas, services, models
from .services import qr_service
from weezy_cbs.core_infrastructure_config_engine.api import get_current_active_user

router = APIRouter(
    tags=["NQR Payments (NIBSS Standard)"],
)

@router.post("/generate", response_model=schemas.QRCodeResponse)
async def generate_my_qr(
    qr_in: schemas.QRCodeBase,
    db: Session = Depends(get_db),
    current_user: Any = Depends(get_current_active_user)
):
    """Generates a personal or business QR code for collections."""
    from weezy_cbs.customer_identity_management.models import Customer
    customer = db.query(Customer).first() # Demo
    
    create_req = schemas.QRCodeCreate(
        **qr_in.dict(),
        customer_id=customer.id
    )
    return qr_service.generate_qr(db, create_req)

@router.post("/scan")
async def scan_and_decode_qr(
    request: schemas.QRScanRequest,
    db: Session = Depends(get_db),
    current_user: Any = Depends(get_current_active_user)
):
    """Decodes a scanned QR payload and returns recipient info."""
    try:
        return qr_service.decode_qr(db, request.qr_payload)
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@router.post("/pay")
async def pay_via_qr(
    request: schemas.QRPaymentRequest,
    db: Session = Depends(get_db),
    current_user: Any = Depends(get_current_active_user)
):
    """Executes a payment to a scanned QR recipient."""
    from weezy_cbs.customer_identity_management.models import Customer
    customer = db.query(Customer).first() # Demo
    return await qr_service.process_qr_payment(db, customer.id, request)

@router.get("/my-codes", response_model=List[schemas.QRCodeResponse])
async def list_my_qr_codes(
    db: Session = Depends(get_db),
    current_user: Any = Depends(get_current_active_user)
):
    """Returns all QR codes generated by the user."""
    from weezy_cbs.customer_identity_management.models import Customer
    customer = db.query(Customer).first()
    return db.query(models.QRCode).filter(models.QRCode.customer_id == customer.id).all()
