"""add_kyc_bvn_nin_tier_to_user

Revision ID: d187b05177fd
Revises: d3af2530152e
Create Date: 2025-07-01 16:35:23.617434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd187b05177fd'
down_revision: Union[str, Sequence[str], None] = 'd3af2530152e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bvn', sa.String(length=11), nullable=True))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nin', sa.String(length=11), nullable=True))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyc_doc_references', sa.String(), nullable=True))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_tier', sa.Enum('TIER1', 'TIER2', 'TIER3', name='accounttier'), nullable=False, server_default='TIER1'))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sme_customer', sa.Boolean(), nullable=True)) # Model default is False, column is nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('kyc_status',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=False,
                              existing_server_default=sa.text("'NOT_INITIATED'"))

    # Create indexes separately, this is generally fine outside batch for SQLite
    op.create_index(op.f('ix_users_bvn'), 'users', ['bvn'], unique=True)
    op.create_index(op.f('ix_users_nin'), 'users', ['nin'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###
    # Drop indexes first
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_nin'), table_name='users')
    op.drop_index(op.f('ix_users_bvn'), table_name='users')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('kyc_status',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=True,
                              existing_server_default=sa.text("'NOT_INITIATED'"))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_sme_customer')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_tier')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kyc_doc_references')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nin')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bvn')
    # ### end Alembic commands ###
